/* ==========================================================================
   Marginalia · Concept Cards panel
   --------------------------------------------------------------------------
   Renders an interactive grid of concept cards generated by the
   `concept-cards` (or `argument-breakdown`) AI features.
   ========================================================================== */

import { PanelRegistry } from './registry.js';

const RELATION_LABELS = {
  'core-thesis':   'Core thesis',
  'supports':      'Supporting',
  'questions':     'Questions',
  'action-trigger': 'Action trigger',
};

function esc(s) {
  return String(s ?? '').replace(/[&<>"]/g, c =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] ?? c));
}

function renderConceptCards(book, container) {
  const data = book?._aiData?.['concept-cards']
            || book?._aiData?.['argument-breakdown']
            || book?.graph?.concepts;
  if (!Array.isArray(data) || data.length === 0) {
    container.innerHTML = `<div class="panel-empty">
      <p class="panel-empty__label">Concepts not yet generated.</p>
    </div>`;
    return;
  }

  const cardsHtml = data.map(concept => {
    const strengthPct = Math.round((Number(concept.strength) || 0.5) * 100);
    const relationLabel = RELATION_LABELS[concept.relationType] || esc(concept.relationType || '');
    return `
      <article class="concept-card" data-relation="${esc(concept.relationType || '')}">
        <header class="concept-card__header">
          <h3 class="concept-card__name">${esc(concept.name)}</h3>
          ${concept.contextTag ? `<span class="concept-card__tag">${esc(concept.contextTag)}</span>` : ''}
        </header>
        ${concept.aliases?.length ? `
          <p class="concept-card__aliases">${concept.aliases.map(esc).join(' · ')}</p>
        ` : ''}
        <div class="concept-card__strength">
          <span class="concept-card__relation-label">${relationLabel}</span>
          <div class="concept-card__strength-bar">
            <div class="concept-card__strength-fill" style="width:${strengthPct}%"></div>
          </div>
        </div>
        ${concept.description ? `<p class="concept-card__description">${esc(concept.description)}</p>` : ''}
        ${concept.readerUnderstanding ? `
          <div class="concept-card__reader">
            <span class="concept-card__reader-label">My Understanding</span>
            <p class="concept-card__reader-text">${esc(concept.readerUnderstanding)}</p>
          </div>
        ` : ''}
      </article>
    `;
  }).join('');

  container.innerHTML = `<div class="concept-cards-grid">${cardsHtml}</div>`;
}

PanelRegistry.set('concept-cards', renderConceptCards);

export { renderConceptCards };
